const { _electron: electron, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
(async () => {
 const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'cairn-search-'));
 const launch = process.env.HARBOR_PACKAGED ? { executablePath: path.resolve('release/Cairn-darwin-arm64/Cairn.app/Contents/MacOS/Cairn'), args: [] } : { args: [process.cwd()] };
 const app = await electron.launch({ ...launch, args: [...launch.args, `--user-data-dir=${profile}`], env: { ...process.env, ELECTRON_RUN_AS_NODE: '' } });
 try {
  const page = await app.firstWindow(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.locator('.session-item').waitFor();
  const first = await page.locator('.session-item').getAttribute('data-id');
  const send = (id, data) => page.evaluate(({id,data}) => window.harbor.input(id,data), {id,data});
  await send(first, "printf '\\nSEARCH%s\\nsearch%s\\n中文%s\\n' _needle _needle _测试; for i in {1..100}; do echo filler-$i; done\r");
  await expect(page.locator('.terminal-pane:not([hidden]) .xterm-screen')).toContainText('filler-100');
  await page.locator('.xterm-helper-textarea').press('Meta+f');
  await expect(page.locator('#search-input')).toBeFocused();
  await page.locator('#search-input').fill('SEARCH_needle');
  await expect(page.locator('#search-count')).toHaveText(/\d \/ 2/);
  const count = await page.locator('#search-count').textContent();
  await page.locator('#search-input').press('Enter');
  assert.notEqual(await page.locator('#search-count').textContent(), count);
  await page.locator('#search-input').press('Shift+Enter');
  await expect(page.locator('#search-count')).toHaveText(count);
  await page.locator('#search-input').press('ArrowDown');
  assert.notEqual(await page.locator('#search-count').textContent(), count);
  await page.locator('#search-input').press('ArrowUp');
  await expect(page.locator('#search-count')).toHaveText(count);
  await expect(page.locator('#search-input')).toHaveValue('SEARCH_needle');
  await page.locator('#search-case').click();
  await expect(page.locator('#search-count')).toHaveText('1 / 1');
  await page.locator('#search-input').fill('中文_测试');
  await expect(page.locator('#search-count')).toHaveText('1 / 1');
  await page.locator('#search-input').fill('nothing_matches_here');
  await expect(page.locator('#search-count')).toHaveText('无匹配');
  await page.locator('#search-input').fill('');
  await expect(page.locator('#search-count')).toHaveText('');
  await page.locator('#search-input').fill('SEARCH_needle');
  await page.locator('#new-terminal').click();
  await expect(page.locator('#search-count')).toHaveText('无匹配');
  await page.locator(`.session-item[data-id="${first}"]`).click();
  await expect(page.locator('#search-count')).toHaveText('1 / 1');
  await send(first, "printf '\\nSEARCH%s\\n' _needle\r");
  await expect(page.locator('#search-count')).toHaveText(/\d \/ 2/);
  await page.locator('#search-input').focus();
  await page.locator('#search-input').press('Escape');
  await expect(page.locator('#search-bar')).toBeHidden();
  await expect(page.locator('.terminal-pane:not([hidden]) .xterm-helper-textarea')).toBeFocused();
  await page.keyboard.type("printf '\\nFOCUS_%s\\n' ok"); await page.keyboard.press('Enter');
  await expect(page.locator('.terminal-pane:not([hidden]) .xterm-screen')).toContainText('FOCUS_ok');
  await page.locator('#search-toggle').click();
  await page.locator('#search-input').fill('SEARCH_needle');
  fs.mkdirSync('test-results', {recursive:true});
  await page.locator('#settings-toggle').click(); await page.locator('#theme').selectOption('dark'); await page.keyboard.press('Escape');
  await page.locator('#search-next').click();
  await expect(page.locator('.terminal-pane:not([hidden]) .xterm-screen')).toContainText('SEARCH_needle');
  await page.screenshot({path:'test-results/search-dark.png'});
  await page.locator('#settings-toggle').click(); await page.locator('#theme').selectOption('light'); await page.keyboard.press('Escape');
  await app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].setSize(740, 600));
  await page.locator('#search-next').click();
  await expect(page.locator('.terminal-pane:not([hidden]) .xterm-screen')).toContainText('SEARCH_needle');
  await expect(page.locator('#search-count')).toHaveText(/\d \/ 2/);
  await page.screenshot({path:'test-results/search-light.png'});
  assert.equal(errors.length, 0, errors.join('\n'));
  console.log('PASS: search scrollback, navigation, case, Chinese, empty/no match, session isolation, live output, Escape focus, themes and narrow window.');
 } finally {
  const exited = new Promise(resolve => app.process().once('exit',resolve));
  await app.evaluate(({app}) => app.exit(0)); await exited;
  fs.rmSync(profile,{recursive:true,force:true});
 }
})().catch(e => {console.error(e);process.exitCode=1;});
