const { _electron: electron } = require('@playwright/test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
(async () => {
  const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'cairn-smoke-'));
  const launch = process.env.HARBOR_PACKAGED ? { executablePath: path.resolve(__dirname, '../release/Cairn-darwin-arm64/Cairn.app/Contents/MacOS/Cairn'), args: [] } : { args: [path.resolve(__dirname, '..')] };
  const app = await electron.launch({ ...launch, args: [...launch.args, `--user-data-dir=${profile}`], env: { ...process.env, ELECTRON_RUN_AS_NODE: '' } });
  try {
    const page = await app.firstWindow();
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.locator('.session-item').waitFor();
    const first = await page.locator('.session-item').getAttribute('data-id');
    await page.locator('.terminal-pane:not([hidden]) .xterm-helper-textarea').pressSequentially("printf '\\nKEYBOARD_%s\\n' ready");
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => document.querySelector('.xterm-screen')?.textContent.includes('KEYBOARD_ready'));
    const terminalText = () => page.locator('.terminal-pane:not([hidden]) .xterm-screen').innerText();
    await page.evaluate(id => window.harbor.input(id, "export HARBOR_TEST=first; printf '\\nREADY_%s\\n' $HARBOR_TEST\r"), first);
    await page.waitForFunction(() => document.querySelector('.terminal-pane:not([hidden]) .xterm-screen')?.textContent.includes('READY_first'));
    await page.locator('#new-terminal').click();
    await page.waitForFunction(() => document.querySelectorAll('.session-item').length === 2);
    const second = await page.locator('.session-item.active').getAttribute('data-id');
    assert.notEqual(first, second);
    await page.evaluate(id => window.harbor.input(id, "printf '\\nISOLATED_%s\\n' ${HARBOR_TEST:-yes}\r"), second);
    await page.waitForFunction(() => document.querySelector('.terminal-pane:not([hidden]) .xterm-screen')?.textContent.includes('ISOLATED_yes'));
    await page.evaluate(id => window.harbor.input(id, "sleep 1; printf '\\nBACKGROUND_%s\\n' done\r"), first);
    await page.locator(`.session-item[data-id="${first}"] .unread`).waitFor();
    await page.waitForTimeout(1400);
    await page.locator(`.session-item[data-id="${first}"]`).click();
    await page.waitForFunction(() => document.querySelector('.terminal-pane:not([hidden]) .xterm-screen')?.textContent.includes('BACKGROUND_done'));
    assert((await terminalText()).includes('READY_first'));
    await page.locator('#rename').click(); await page.locator('#name-input').fill('前端开发'); await page.locator('.primary').click();
    assert.equal(await page.locator('#active-title').textContent(), '前端开发');
    await page.locator('#settings-toggle').click(); await page.locator('#theme').selectOption('light'); await page.locator('#font-size').fill('16'); await page.locator('#font-size').dispatchEvent('change'); await page.keyboard.press('Escape');
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
    await page.locator('#settings-toggle').click(); await page.locator('#theme').selectOption('dark'); await page.locator('#font-size').fill('14'); await page.locator('#font-size').dispatchEvent('change'); await page.keyboard.press('Escape');
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(980, 660));
    await page.waitForTimeout(250);
    const dims = await page.locator('#dimensions').textContent();
    await page.evaluate(id => window.harbor.input(id, "stty size\r"), first);
    const [cols, rows] = dims.split(' × ').map(Number);
    await page.waitForFunction(({cols,rows}) => document.querySelector('.terminal-pane:not([hidden]) .xterm-screen')?.textContent.includes(`${rows} ${cols}`), {cols,rows});
    await page.evaluate(id => window.harbor.input(id, 'sleep 20\r'), second);
    await page.waitForTimeout(200);
    await page.evaluate(id => window.harbor.input(id, '\x03'), second);
    await page.evaluate(id => window.harbor.input(id, "printf '\\nINTERRUPT_%s\\n' ok\r"), second);
    await page.locator(`.session-item[data-id="${second}"]`).click();
    await page.waitForFunction(() => document.querySelector('.terminal-pane:not([hidden]) .xterm-screen')?.textContent.includes('INTERRUPT_ok'));
    fs.mkdirSync('test-results', { recursive: true });
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1220, 800));
    await page.locator('.session-item').first().click();
    await page.waitForTimeout(200);
    await page.screenshot({ path: 'test-results/harbor.png' });
    await page.locator('.session-item').nth(1).click();
    await page.evaluate(id => window.harbor.input(id, 'exit\r'), second);
    await page.waitForFunction(() => document.querySelector('#session-state').dataset.state === 'ended');
    await page.locator('#close-terminal').click();
    await page.waitForFunction(() => document.querySelectorAll('.session-item').length === 1);
    await page.evaluate(id => window.harbor.input(id, 'exit\r'), first);
    await page.waitForFunction(() => document.querySelector('#session-state').dataset.state === 'ended');
    await page.locator('#close-terminal').click();
    await page.locator('#empty').waitFor({ state: 'visible' });
    assert.equal(errors.length, 0, errors.join('\n'));
    fs.mkdirSync('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/empty.png' });
    console.log('PASS: real zsh, isolated environments, background output, switch retention, rename, themes, resize, Ctrl+C, exit, close, empty state; no renderer errors.');
  } finally {
    const exited = new Promise(resolve => app.process().once('exit', resolve));
    await app.evaluate(({ app }) => app.exit(0)); await exited;
    await fs.promises.rm(profile, { recursive: true, force: true, maxRetries: 10, retryDelay: 200 });
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
